// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import starlightBlog from 'starlight-blog';

const SITE = 'https://retroxr.app';
const GAME_REPO = 'https://github.com/XenuIsWatching/RetroXR';

export default defineConfig({
	// A custom domain serves from the root, so there is no `base` here. Setting one
	// would break every internal link.
	site: SITE,
	integrations: [
		starlight({
			title: 'RetroXR',
			description:
				'A VR retro-gaming room where the hardware is real — pick up a console, ' +
				'run a cable to the TV, push the cartridge in and hit power. Powered by libretro.',
			logo: {
				// Two files, not one: the wordmark's "Retro" is near-white and vanished
				// into the light theme's own near-white nav bar. Starlight swaps these
				// on the site's theme, which a media query inside a single SVG cannot
				// do -- it is loaded as an <img> and cannot see the page's data-theme.
				light: './src/assets/retroxr-lockup-header-light.svg',
				dark: './src/assets/retroxr-lockup-header.svg',
				alt: 'RetroXR',
				replacesTitle: true,
			},
			favicon: '/favicon.svg',
			customCss: ['./src/styles/brand.css'],
			components: {
				// Starlight has no built-in Ko-fi icon, so the header's social row is
				// extended rather than replaced.
				SocialIcons: './src/components/SocialIcons.astro',
			},
			social: [
				{ icon: 'github', label: 'GitHub', href: GAME_REPO },
				{ icon: 'discord', label: 'Discord', href: 'https://discord.gg/mdjdBDTdW' },
			],
			editLink: {
				baseUrl: 'https://github.com/XenuIsWatching/retroxr-site/edit/main/',
			},
			lastUpdated: true,
			head: [
				{ tag: 'meta', attrs: { property: 'og:image', content: `${SITE}/og.jpg` } },
				{ tag: 'meta', attrs: { name: 'twitter:image', content: `${SITE}/og.jpg` } },
				{ tag: 'meta', attrs: { name: 'twitter:card', content: 'summary_large_image' } },
				{ tag: 'meta', attrs: { name: 'theme-color', content: '#0b0f1c' } },
			],
			plugins: [
				starlightBlog({
					title: 'Devlog',
					navigation: 'header-end',
					postCount: 10,
					recentPostCount: 5,
					metrics: { readingTime: true },
					authors: {
						ryan: {
							name: 'Ryan McClelland',
							title: 'Author',
							url: 'https://github.com/XenuIsWatching',
						},
					},
				}),
			],
			sidebar: [
				{
					label: 'Get started',
					items: [
						{ label: 'Download & install', slug: 'download' },
						{ label: 'Your first session', slug: 'guide/first-run' },
						{ label: 'Adding your games', slug: 'guide/adding-games' },
					],
				},
				{ label: 'Playing', items: [{ autogenerate: { directory: 'guide/playing' } }] },
				{ label: 'Cores & BIOS', items: [{ autogenerate: { directory: 'guide/cores' } }] },
				// Listed rather than autogenerated, so the Super Famicom's three
				// cartridge-shaped machines sit UNDER the console they go into. They are
				// not platforms beside it — you cannot own a Sufami Turbo without a Super
				// Nintendo — and the flat list said otherwise. The cost is that a new
				// platform page has to be added here as well as written.
				{
					label: 'Platforms',
					items: [
						'guide/platforms/wii',
						'guide/platforms/nes',
						{
							label: 'Super Nintendo',
							items: [
								'guide/platforms/super-nintendo',
								'guide/platforms/satellaview',
								'guide/platforms/sufami-turbo',
							],
						},
						'guide/platforms/sega-genesis',
						'guide/platforms/nintendo-64',
						'guide/platforms/playstation',
						'guide/platforms/atari-2600',
						'guide/platforms/ds-and-3ds',
						'guide/platforms/virtual-boy',
						'guide/platforms/psp',
					],
				},
				{ label: 'The rest of the room', items: [{ autogenerate: { directory: 'guide/room' } }] },
				{ label: 'Connecting things', items: [{ autogenerate: { directory: 'guide/connecting' } }] },
				{ label: 'Reference', items: [{ autogenerate: { directory: 'guide/reference' } }] },
			],
		}),
	],
});
